const data = {
  id: "cs_test_a1Y21jvIpxvU2SZcCsL3LNbFANlHduUJ8ppLhYILn9kZ5CDCnnhhRAxbqi",
  object: "checkout.session",
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 2230,
  amount_total: 2230,
  automatic_tax: { enabled: false, liability: null, status: null },
  billing_address_collection: null,
  cancel_url: "http://localhost:3000/failure",
  client_reference_id: null,
  client_secret: null,
  consent: null,
  consent_collection: null,
  created: 1706965211,
  currency: "gbp",
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null,
  },
  customer: null,
  customer_creation: "if_required",
  customer_details: {
    address: {
      city: "Gandhinagar",
      country: "GB",
      line1: "gandhi",
      line2: "sector 27 samarapan circle home no.861",
      postal_code: "382027",
      state: null,
    },
    email: "admin@gmail.com",
    name: "Hardik Bhammar",
    phone: null,
    tax_exempt: "none",
    tax_ids: [],
  },
  customer_email: null,
  expires_at: 1707051611,
  invoice: null,
  invoice_creation: {
    enabled: false,
    invoice_data: {
      account_tax_ids: null,
      custom_fields: null,
      description: null,
      footer: null,
      issuer: null,
      metadata: {},
      rendering_options: null,
    },
  },
  livemode: false,
  locale: null,
  metadata: {
    images:
      '["https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg"]',
    email: "hardikbhammar808@gmail.com",
  },
  mode: "payment",
  payment_intent: "pi_3OfiqISCNlaf5syu03vm7gDZ",
  payment_link: null,
  payment_method_collection: "always",
  payment_method_configuration_details: null,
  payment_method_options: {},
  payment_method_types: ["card"],
  payment_status: "paid",
  phone_number_collection: { enabled: false },
  recovered_from: null,
  setup_intent: null,
  shipping_address_collection: { allowed_countries: ["GB", "US", "IN"] },
  shipping_cost: null,
  shipping_details: {
    address: {
      city: "Gandhinagar",
      country: "GB",
      line1: "gandhi",
      line2: "sector 27 samarapan circle home no.861",
      postal_code: "382027",
      state: "",
    },
    name: "Hardik Bhammar",
  },
  shipping_options: [],
  status: "complete",
  submit_type: null,
  subscription: null,
  success_url: "http://localhost:3000/success",
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  ui_mode: "hosted",
  url: null,
};
